version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: echo Hello, I\'m running.

      - run:
          name: Install dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3
            sudo curl -O https://bootstrap.pypa.io/get-pip.py
            python3 get-pip.py --user
            export PATH=$PATH:/home/circleci/.local/bin
            pip install awscli --upgrade --user
      
      - run: echo Another greeting after installing dependencies.

      - run:
          name: Push file to S3
          command: aws s3 sync ~/data.txt s3://sanggon-test/ --delete