version: 2
jobs:
  prepare:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: echo Hello, I\'m running.
      - run: echo `pwd`
      - run: echo `ls`
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3
            sudo curl -O https://bootstrap.pypa.io/get-pip.py
            python3 get-pip.py --user
            export PATH=$PATH:/home/circleci/.local/bin
            pip install awscli --upgrade --user

  deploy:
    steps:
      - checkout
      - run:
          name: Push to S3
          command: |
            aws s3 cp /home/circleci/project/data.txt s3://sanggon-test/foo/dataa.txt

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - prepare
      - deploy:
          requires:
            - prepare
          filters:
            branches:
              only: master