version: 2
jobs:
  prepare:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            export PATH=$PATH:/home/circleci/.local/bin
            pip install awscli --upgrade --user

  deploy:
    machine:
      enabled: true

    steps:
      - checkout
      - run:
          name: Push to S3
          command: |
            aws s3 cp /home/circleci/project/data.txt s3://sanggon-test/foo/dataa.txt

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - prepare
      - deploy:
          requires:
            - prepare
          filters:
            branches:
              only: master