version: 2
jobs:
  log:
    machine:
      enabled: true
    steps:
      - run: echo Start

  build:
    working_directory: /tmp
    docker:
      - image: buildpack-deps:jessie
    steps:
      - run: pwd
      - run: mkdir -p workspace
      - run: echo "fooo" > workspace/foo.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - foo.txt

  prepare:
    working_directory: /tmp
    docker:
      - image: buildpack-deps:jessie

    steps:
      - run: pwd
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/foo.txt
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            export PATH=$PATH:/home/circleci/.local/bin
            pip install awscli --upgrade --user

  deploy:
    machine:
      enabled: true

    steps:
      - checkout
      - run:
          name: Push to S3
          command: |
            aws s3 cp /home/circleci/project/data.txt s3://sanggon-test/foo/dataa.txt

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - prepare:
          requires:
            - build
      - deploy:
          requires:
            - prepare
          filters:
            branches:
              only: master